### ISSUE TITLE
publish 报错

### ISSUE THREAD

**Issue by i-tengfei** [spmjs/spm-yuan#1]
信息如下

服务端：

```
stream.js:52
  dest.on('drain', ondrain);
       ^
TypeError: Object [object Object] has no method 'on'
    at IncomingMessage.Stream.pipe (stream.js:52:8)
    at module.exports.async.waterfall._.extend.updated_at (/usr/local/lib/node_m
odules/spm-yuan/lib/action/update-module.js:24:17)
    at async.iterator.fn (/usr/local/lib/node_modules/spm-yuan/node_modules/asyn
c/lib/async.js:579:34)
    at async.waterfall.wrapIterator (/usr/local/lib/node_modules/spm-yuan/node_m
odules/async/lib/async.js:495:34)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

客户端：

```
      parse: package.json
       read: package.json
     verify: family in package.json
     verify: name in package.json
     verify: version in package.json
    publish: gallery/jquery@2.0.2
     verify: dist directory
    tarfile: jquery-2.0.2.tar.gz
    tarfile: ~\AppData\Local\Temp\gallery\jquery-2.0.2.tar.gz
       post: http://xxx.xxxxxx.com:8400/repository/gallery/jquery/2.0.2/
        put: http://xxx.xxxxxx.com:8400/repository/gallery/jquery/2.0.2/
       exit: socket hang up
```

node 版本
v0.8.14

spm 版本
2.1.4

求帮助~

**Comment by lepture** [comment]
``` js
req.pipe(verifier, {end : false});
```

@edokeh 可以往 hash 上 pipe 的？

**Comment by i-tengfei** [comment]
把MD5校验部分注释掉，暂时可以使用了，等待修复~

**Comment by edokeh** [comment]
请问是不是用了HTTP代理？
我之前确实发现用了代理的时候，不管上传什么文件，MD5 码都是一样
@lepture 可有建议？

**Comment by edokeh** [comment]
呃，用 0.8.14 试验了一下，确实会有这个报错

查了一下 [0.8.14的API](http://nodejs.org/dist/v0.8.14/docs/api/crypto.html#crypto_class_verify)，发现这个版本的 Node 中 verifier 貌似还不是 stream 对象
而根据[最新的文档](http://nodejs.org/api/crypto.html#crypto_class_verify)

> Verify objects are writable streams

所以是可以 pipe 的

**这个问题只需要安装 0.10 版本的 Node 就能解决了**

PS：因为我最近才开始正式开始写 Node.js ，所有的东西都是依照最新的程序和文档来做，所以对以往的变迁历史不太清楚
不知道 Node 社区对于自身版本的支持一般是采用什么策略？保持兼容老版本？还是放弃并要求用户升级到最新？
@lepture 求建议

**Comment by lepture** [comment]
@edokeh 让 @mrtone 升级 node 吧。
