### ISSUE TITLE
加入镜像同步的功能

### ISSUE THREAD

**Issue by edokeh** [spmjs/spm-yuan#3]
执行 Install 时如果本地没有找到相应模块，会自动从远程镜像上获取

spmjs/spm#697

**Comment by rocketxujia** [comment]
我们团队使用了spm-yuan作为源服务器。看readme说明，目前spm-yuan默认会以 http://spmjs.org 为远程官方源 ，但为什么我尝试了安装alice下的模块没安装成功

```
jomatoMacBook-Pro:index xujia$ spm install alice/nav

        install: alice/nav@stable
          fetch: alice/nav@stable
           yuan: alice/nav not found! dns.js:113
      throw new Error('invalid argument: `family` must be 4 or 6');
            ^
Error: invalid argument: `family` must be 4 or 6
    at Object.exports.lookup (dns.js:113:13)
    at Socket.connect (net.js:914:20)
    at Agent.exports.connect.exports.createConnection (net.js:86:35)
    at Agent.createSocket (_http_agent.js:194:16)
    at Agent.addRequest (_http_agent.js:166:23)
    at new ClientRequest (_http_client.js:147:16)
    at Object.exports.request (http.js:52:10)
    at Request.start (/usr/local/lib/node_modules/spm/node_modules/request/index.js:604:30)
    at Request.end (/usr/local/lib/node_modules/spm/node_modules/request/index.js:1211:28)
    at /usr/local/lib/node_modules/spm/node_modules/request/index.js:436:12
           warn: not in cache
          error: not found
```
