### ISSUE TITLE
客户端spm install xxx, 导致源服务意外退出。

### ISSUE THREAD

**Issue by ronnin** [spmjs/spm-yuan#5]
某客户端通过这个应用搭建的spm源，spm install 某组件，偶尔会导致源服务意外退出。node进程就退出了。

今天一天遇到3次，但是没终结出规律。以下是意外退出前最后的日志：

```
[SPM Install] arale/popup
- - - [Thu, 26 Sep 2013 09:16:54 GMT] "GET /repository/arale/popup/ HTTP/1.0" 500 333 "-" "spm (2.1.12, v0.10.19, linux x64)"
latestPkg: undefined

/usr/lib/node_modules/spm-yuan/node_modules/underscore/underscore.js:783
      if (key in obj) copy[key] = obj[key];
              ^
TypeError: Cannot use 'in' operator to search for 'family' in undefined
    at /usr/lib/node_modules/spm-yuan/node_modules/underscore/underscore.js:783:18
    at Array.forEach (native)
    at _.each._.forEach (/usr/lib/node_modules/spm-yuan/node_modules/underscore/underscore.js:78:11)
    at Function._.pick (/usr/lib/node_modules/spm-yuan/node_modules/underscore/underscore.js:782:5)
    at /usr/lib/node_modules/spm-yuan/lib/models/project.js:46:30
    at fn (/usr/lib/node_modules/spm-yuan/node_modules/async/lib/async.js:579:34)
    at Object._onImmediate (/usr/lib/node_modules/spm-yuan/node_modules/async/lib/async.js:495:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by edokeh** [comment]
猜测应该是初始化源数据时候出了问题，原因有不少
麻烦先检查一下这个组件的 family 下是否有不合法的 package.json 存在？

**Comment by edokeh** [comment]
@ronnin
