### ISSUE TITLE
安装报错： Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by KirinHuang** [spmjs/spm-yuan#6]
错误日志如下：
0 info it worked if it ends with ok
1 verbose cli [ 'D:\nodejs\\node.exe',
1 verbose cli   'D:\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'spm-yuan',
1 verbose cli   '-g' ]
2 info using npm@1.3.8
3 info using node@v0.10.18
4 verbose node symlink D:\nodejs\node.exe
5 verbose cache add [ 'spm-yuan', null ]
6 verbose cache add name=undefined spec="spm-yuan" args=["spm-yuan",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'spm-yuan',
7 verbose parsed url   path: 'spm-yuan',
7 verbose parsed url   href: 'spm-yuan' }
8 silly lockFile 09fbb5fd-spm-yuan spm-yuan
9 verbose lock spm-yuan C:\Users\xxx\AppData\Roaming\npm-cache\09fbb5fd-spm-yuan.lock
10 silly lockFile 09fbb5fd-spm-yuan spm-yuan
11 silly lockFile 09fbb5fd-spm-yuan spm-yuan
12 verbose addNamed [ 'spm-yuan', '' ]
13 verbose addNamed [ null, '_' ]
14 silly lockFile 2c265ff3-spm-yuan spm-yuan@
15 verbose lock spm-yuan@ C:\Users\xxx\AppData\Roaming\npm-cache\2c265ff3-spm-yuan.lock
16 silly addNameRange { name: 'spm-yuan', range: '_', hasData: false }
17 verbose url raw spm-yuan
18 verbose url resolving [ 'https://registry.npmjs.org/', './spm-yuan' ]
19 verbose url resolved https://registry.npmjs.org/spm-yuan
20 info trying registry request attempt 1 at 15:02:26
21 http GET https://registry.npmjs.org/spm-yuan
22 info retry will retry, error on last attempt: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
23 info trying registry request attempt 2 at 15:02:36
24 http GET https://registry.npmjs.org/spm-yuan
25 info retry will retry, error on last attempt: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
26 info trying registry request attempt 3 at 15:03:36
27 http GET https://registry.npmjs.org/spm-yuan
28 silly lockFile 2c265ff3-spm-yuan spm-yuan@
29 silly lockFile 2c265ff3-spm-yuan spm-yuan@
30 error Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
30 error     at SecurePair.<anonymous> (tls.js:1357:32)
30 error     at SecurePair.EventEmitter.emit (events.js:92:17)
30 error     at SecurePair.maybeInitFinished (tls.js:970:10)
30 error     at CleartextStream.read [as _read](tls.js:463:15)
30 error     at CleartextStream.Readable.read (_stream_readable.js:320:10)
30 error     at EncryptedStream.write [as _write](tls.js:366:25)
30 error     at doWrite (_stream_writable.js:221:10)
30 error     at writeOrBuffer (_stream_writable.js:211:5)
30 error     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
30 error     at write (_stream_readable.js:583:24)
31 error If you need help, you may report this log at:
31 error     http://github.com/isaacs/npm/issues
31 error or email it to:
31 error     npm-@googlegroups.com
32 error System Windows_NT 6.1.7601
33 error command "D:\nodejs\\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "install" "spm-yuan" "-g"
34 error cwd C:\Users\xxx
35 error node -v v0.10.18
36 error npm -v 1.3.8
37 verbose exit [ 1, true ]

**Comment by KirinHuang** [comment]
知道问题了，是我这边的gae代理的问题，关掉就好了。
